# Paramètres généraux d'application
application_position_largeur: 250
application_position_hauteur: 40
application_largeur: 750
application_hauteur: 250
interface_foncee: false

# Paramètres de l'onglet de paramètres
## Limite du slider
qualite_min: 200
qualite_max: 4000

# Onglet 4
onglet_4_mise_en_page: 0 # 0 ou 1
## Paramètres de l'hémicycle
### Organisation des points
n_rangees: 9
points_base: 15
points_increment: 4
### Couleurs des continents
couleurs_continents:
  Africa: '#F0E68C'
  Antarctica: '#A7C9E6'
  Asia: '#EE211E'
  Europe: '#9A0EE6'
  North America: '#1310CE'
  Oceania: '#1EC3CF'
  South America: '#23E958'
lighter_value: 190
## Paramètres du top pays visités
top_n_pays: null # null pour tous les avoir
pct_ndigits: 0
